version: "3.3"

services:
  store-web:
    build:
      context: ./front-end/store-web
      dockerfile: .dockerfile
    ports:
      - "3000:3000"
    volumes:
      - eshopping:/var/opt/store-web

  admin-web:
    build:
      context: ./front-end/admin-web
      dockerfile: .dockerfile
    ports:
      - "4000:4000" 
    volumes:
      - eshopping:/var/opt/admin-web
      
volumes:
  eshopping:
