import { Inventory } from "constants/icons.constants";
import { PermissionKeys } from "constants/permission-key.constants";
import MaterialManagement from "./material";

import MaterialCategoryManagement from "./material-category/material-category-management.page";
import MaterialDetail from "./material/detail-material";
import EditMaterialPage from "./material/edit-material.page";
import ImportMaterial from "./material/import-material";
import NewMaterialPage from "./material/new-material.page";
import PurchaseOrder from "./purchase-order";
import DetailPurchaseOrder from "./purchase-order/detail-purchase-order";
import EditPurchaseOrder from "./purchase-order/edit-purchase-oder";
import AddNewPurchaseOrder from "./purchase-order/new-purchase-order/new-purchase-order.page";
import Supplier from "./supplier";
import SupplierDetail from "./supplier/components/detail-supplier.component";
import EditSupplier from "./supplier/components/edit-supplier.component";

import i18n from "utils/i18n";
import InventoryHistoryPage from "./inventory-history/inventory-history.page";
import NewTransferMaterialComponent from "./material-transfer-list/new-transfer-material/new-transfer-material.page";
import ImportPurchaseOrderPage from "./purchase-order/import-purchase-order/import-purchase-order.page";
import TransferMaterialHistory from "./transfer-material-history/transfer-material-history.page";
import EditTransferMaterial from "./transfer-material/edit-transfer-material";
import { TransferMaterialManagement } from "./transfer-material/transfer-material-management/transfer-material-management.page";
import ViewTransferMaterial from "./transfer-material/view-transfer-material/view-transfer-material.page";

const { t } = i18n;

const route = {
  key: "app.inventory",
  position: 2,
  path: "#",
  icon: <Inventory />,
  name: t("menu.inventory"),
  isMenu: true,
  exact: true,
  auth: true,
  child: [
    {
      key: "app.inventory.material",
      position: 2,
      path: "/inventory/material",
      name: t("menu.inventoryManagement.material"),
      isMenu: true,
      exact: true,
      auth: true,
      permission: PermissionKeys.VIEW_MATERIAL,
      component: MaterialManagement,
      child: [],
    },
    {
      key: "app.inventory.material.new",
      focus: "app.inventory.material",
      position: 2,
      path: "/material/add-new",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.CREATE_MATERIAL,
      component: NewMaterialPage,
      child: [],
    },
    {
      key: "app.inventory.material",
      position: 2,
      path: "/inventory/material/edit-material/:id",
      name: "EditMaterialManagement",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.EDIT_MATERIAL,
      component: EditMaterialPage,
      child: [],
    },
    {
      key: "app.inventory.material",
      position: 2,
      path: "/inventory/material/detail/:id",
      name: "MaterialDetail",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.VIEW_MATERIAL,
      component: MaterialDetail,
      child: [],
    },
    {
      key: "app.inventory.material",
      position: 2,
      path: "/inventory/material/import",
      name: "MaterialImport",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.IMPORT_MATERIAL,
      component: ImportMaterial,
      child: [],
    },
    {
      key: "app.inventory.material-category",
      position: 2,
      path: "/inventory/material-category",
      name: t("menu.inventoryManagement.materialCategory"),
      isMenu: true,
      exact: true,
      auth: true,
      permission: PermissionKeys.VIEW_MATERIAL_CATEGORY,
      component: MaterialCategoryManagement,
      child: [],
    },
    {
      key: "app.inventory.supplier",
      position: 2,
      path: "/inventory/supplier",
      name: t("menu.inventoryManagement.supplier"),
      isMenu: true,
      exact: true,
      auth: true,
      permission: PermissionKeys.VIEW_SUPPLIER,
      component: Supplier,
      child: [],
    },
    {
      key: "app.inventory.supplier",
      position: 2,
      path: "/inventory/supplier/:id",
      name: "SupplierDetail",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.VIEW_SUPPLIER,
      component: SupplierDetail,
      child: [],
    },
    {
      key: "app.inventory.purchase-order",
      position: 2,
      path: "/inventory/purchase-orders",
      name: t("menu.inventoryManagement.purchaseOrder"),
      isMenu: true,
      exact: true,
      auth: true,
      permission: PermissionKeys.VIEW_PURCHASE,
      component: PurchaseOrder,
      child: [],
    },
    {
      key: "app.inventory.purchase-order",
      position: 2,
      path: "/inventory/purchase-order/create-new",
      name: "Create Purchase Order",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.CREATE_PURCHASE,
      component: AddNewPurchaseOrder,
      child: [],
    },
    {
      key: "app.inventory.purchase-order",
      position: 2,
      path: "/inventory/edit-purchase-order/:id",
      name: "Edit Purchase Order",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.EDIT_PURCHASE,
      component: EditPurchaseOrder,
      child: [],
    },
    {
      key: "app.inventory.purchase-order",
      position: 2,
      path: "/inventory/purchase-orders/import",
      name: "Import Purchase Order",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.CREATE_PURCHASE,
      component: ImportPurchaseOrderPage,
      child: [],
    },
    {
      key: "app.inventory.purchase-order",
      position: 2,
      path: "/inventory/detail-purchase-order/:id",
      name: "Detail Purchase Order",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.VIEW_PURCHASE,
      component: DetailPurchaseOrder,
      child: [],
    },
    {
      key: "app.inventory.supplier.edit-supplier",
      focus: "app.inventory.supplier",
      position: 2,
      path: "/inventory/supplier/edit/:supplierId",
      name: "Supplier",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.VIEW_SUPPLIER,
      component: EditSupplier,
      child: [],
    },
    {
      key: "app.inventory.inventory-history",
      position: 3,
      path: "/inventory/inventory-history",
      name: t("inventoryHistory.title"),
      isMenu: true,
      exact: true,
      auth: true,
      permission: PermissionKeys.VIEW_INVENTORY_HISTORY,
      component: InventoryHistoryPage,
      child: [],
    },
    {
      key: "app.inventory.transfer-material",
      position: 2,
      path: "/inventory/transfer-material",
      name: t("menu.inventoryManagement.transferMaterial"),
      isMenu: true,
      exact: true,
      auth: true,
      permission: PermissionKeys.VIEW_TRANSFER_MATERIAL,
      component: TransferMaterialManagement,
      child: [],
    },
    {
      key: "app.inventory.view-transfer-material",
      focus: "app.inventory.transfer-material",
      position: 2,
      path: "/inventory/transfer-material/view/:id",
      name: t("menu.inventoryManagement.transferMaterial"),
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.VIEW_TRANSFER_MATERIAL,
      component: ViewTransferMaterial,
      child: [],
    },
    {
      key: "app.inventory.transfer-material",
      position: 2,
      path: "/inventory/transfer-material/create-new",
      name: "Create Transfer Material",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.CREATE_NEW_TRANSFER_MATERIAL,
      component: NewTransferMaterialComponent,
      child: [],
    },
    {
      key: "app.inventory.transfer-material-history",
      position: 2,
      path: "/inventory/transfer-material-history",
      name: t("transferMaterialHistory.title"),
      isMenu: true,
      exact: true,
      auth: false,
      permission: PermissionKeys.VIEW_TRANSFER_MATERIAL,
      component: TransferMaterialHistory,
      child: [],
    },
    {
      key: "app.inventory.material-transfer",
      position: 2,
      path: "/inventory/transfer-material/edit/:id",
      name: "Edit Transfer Material",
      isMenu: false,
      exact: true,
      auth: true,
      permission: PermissionKeys.EDIT_TRANSFER_MATERIAL,
      component: EditTransferMaterial,
      child: [],
    },
  ],
};
export default route;
